import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

import Link from "next/link";
import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";
import { GitHubLogoIcon } from "@radix-ui/react-icons";
import { cookies } from "next/headers";
import Examples from "@/components/examples";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import ChatSupport from "@/components/chat/chat-support";


export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
};
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          variables: { colorPrimary: "#000000" },
          elements: {
            formButtonPrimary:
              "bg-black border border-black border-solid hover:bg-white hover:text-black",
            socialButtonsBlockButton:
              "bg-white border-gray-200 hover:bg-transparent hover:border-black text-gray-600 hover:text-black",
            socialButtonsBlockButtonText: "font-semibold",
            formButtonReset:
              "bg-white border border-solid border-gray-200 hover:bg-transparent hover:border-black text-gray-500 hover:text-black",
            membersPageInviteButton:
              "bg-black border border-black border-solid hover:bg-white hover:text-black",
            card: "bg-[#fafafa]",
          },
        }}
      >

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <main className="flex h-[calc(100dvh)] flex-col items-center justify-center p-4 md:px-24 py-32 gap-4">
              <div className="flex justify-between max-w-5xl w-full items-center">
                <div className="flex gap-3 md:gap-6 items-center">
                  <Link
                    href="#"
                    className="text-xl sm:text-2xl md:text-4xl font-bold text-gradient"
                  >
                    shadcn-chat
                  </Link>
                  <Examples />
                </div>
                <div className="flex gap-1 items-center">
                  <Link
                    href="https://github.com/jakobhoeg/shadcn-chat"
                    className={cn(
                      buttonVariants({ variant: "ghost", size: "icon" }),
                      "size-7",
                    )}
                  >
                    <GitHubLogoIcon className="size-7" />
                  </Link>
                  <ModeToggle />
                </div>
              </div>

              <div className="z-10 border rounded-lg max-w-5xl w-full h-full text-sm flex">
                {/* Page content */}
                {children}
              </div>

              {/* Footer */}
              <div className="flex justify-between max-w-5xl w-full items-start text-xs md:text-sm text-muted-foreground ">
                <p className="max-w-[150px] sm:max-w-lg">
                  Built by{" "}
                  <a
                    className="font-semibold"
                    href="https://github.com/jakobhoeg/"
                  >
                    Jakob Hoeg
                  </a>
                  . Check out the{" "}
                  <a
                    className="font-semibold"
                    href="https://docs-shadcn-chat.vercel.app/"
                  >
                    documentation
                  </a>
                  to get started.
                </p>
                <p className="max-w-[150px] sm:max-w-lg text-right">
                  Source code available on{" "}
                  <a
                    className="font-semibold"
                    href="https://github.com/jakobhoeg/shadcn-chat"
                  >
                    GitHub
                  </a>
                  .
                </p>
              </div>

              {/* Chat support component */}
              <ChatSupport />
            </main>
          </ThemeProvider>
        </body>
      </ClerkProvider>

    </html>
  );
}
